---
  - name: Playbook Update JupyterHub Config
    hosts: jhub_primary_master 
    vars_files:
      - vars.yml

    tasks:
      - name: Update config file
        template:
          src: "{{ config_template }}"
          dest: "{{ config_filename }}"

      - name: Copy JupyterHub installation config secrets
        copy:
          src: ./{{ config_secrets_filename }}
          dest: ~/

      - name: Helm upgrade jupyterhub
        command: /snap/bin/microk8s helm3 upgrade --cleanup-on-fail {{ release_name }} jupyterhub/jupyterhub --namespace jhub --version={{ chart_version }} --values {{ config_filename }} --values {{ config_secrets_filename }}
